FROM rayproject/ray:2.40.0

USER root

# Cài các thư viện cần thiết
RUN pip install --no-cache-dir \
    python-chess \
    minio \
    requests \
    polars \
    pyarrow \
    wandb \
    python-dotenv

# Chuyển về user ray
USER ray
WORKDIR /home/ray

CMD ["ray", "start", "--block"]