FROM python:3.9-slim

WORKDIR /app

ENV PIP_REQUIRE_HASHES=0

# Install dependencies
COPY docker/dashboard/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    rm -rf ~/.cache/pip

# Copy dashboard code
COPY src/dashboard/ /app/

# Streamlit config
RUN mkdir -p ~/.streamlit && \
    cat <<'EOF' > ~/.streamlit/config.toml
[client]
showErrorDetails = false

[server]
enableCORS = false
enableXsrfProtection = true
headless = true
port = 8501
EOF

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.address=0.0.0.0"]
